spring:
  application:
    name: speislist-backend
  profiles:
    active: dev
  ai:
    mcp:
      server:
        enabled: true
        name: speislist
        version: 1.0.0
        stdio: false
        type: sync
        protocol: streamable

jwt:
  secret: ${JWT_SECRET:defaultsecretkeydefaultsecretkeydefaultsecretkey}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: postgres
    password: my_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
